<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<title>OpenGoto</title>
<link href="/opengoto.css" rel="stylesheet" type="text/css" />
<script src="/mchp.js" type="text/javascript"></script>
</head>
<body>
<div id="header">
  <img src="/images/opengoto.png">
  <ul>
    <li><a href="/protect/config.htm">Network Configuration</a></li>
    <li><a href="/mount.htm">Mount Setting</a></li>
    <li><a href="/gps.htm">GPS Status</a></li>
    <li><a href="/index.htm">Home</a></li></li>
  </ul>
</div>
<div id="CONTENT">
